export const PLACEHOLDER_AVATAR = "/images/assets/avatar.png";

export const AVATAR_IMAGES = [
  "https://fljnffgnpjpfnzqnewxj.supabase.co/storage/v1/object/public/images/avatars/Frame%201.png",
  "https://fljnffgnpjpfnzqnewxj.supabase.co/storage/v1/object/public/images/avatars/Frame%202.png",
  "https://fljnffgnpjpfnzqnewxj.supabase.co/storage/v1/object/public/images/avatars/Frame%203.png",
  "https://fljnffgnpjpfnzqnewxj.supabase.co/storage/v1/object/public/images/avatars/Frame%204.png",
  "https://fljnffgnpjpfnzqnewxj.supabase.co/storage/v1/object/public/images/avatars/Frame%205.png",
  "https://fljnffgnpjpfnzqnewxj.supabase.co/storage/v1/object/public/images/avatars/Frame%206.png",
  "https://fljnffgnpjpfnzqnewxj.supabase.co/storage/v1/object/public/images/avatars/Frame%207.png",
  "https://fljnffgnpjpfnzqnewxj.supabase.co/storage/v1/object/public/images/avatars/Frame%208.png",
];

export const HOBBIES = [
  "Gardening",
  "Cooking",
  "Reading",
  "Writing",
  "Painting",
  "Traveling",
  "Photography",
  "Drawing",
  "Knitting",
  "Cycling",
  "Hiking",
  "Fishing",
  "Swimming",
  "Running",
  "Yoga",
  "Dancing",
  "Singing",
  "Playing Musical Instruments",
  "Bird Watching",
  "Collecting",
  "Baking",
  "Woodworking",
  "Pottery",
  "Scrapbooking",
  "Meditation",
  "Chess",
  "Video Gaming",
  "Blogging",
  "Volunteering",
  "Astronomy",
];
